///////////////////////////////////////////////////////////////////////////////
// TestModule.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TestModule.h"
#include "TMC_File_Test_ProjectVersion.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CTestModule
BEGIN_INTERFACE_MAP(CTestModule)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_IPERSIST_LIB(CTestModule, VID_TMC_File_Test_Project, CID_TMC_File_Test_ProjectCTestModule)
IMPLEMENT_ITCOMOBJECT(CTestModule)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CTestModule)
IMPLEMENT_ITCADI(CTestModule)
IMPLEMENT_ITCWATCHSOURCE(CTestModule)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CTestModule 
BEGIN_SETOBJPARA_MAP(CTestModule)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CTestModule 
BEGIN_GETOBJPARA_MAP(CTestModule)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CTestModule
BEGIN_OBJPARAWATCH_MAP(CTestModule)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CTestModule
BEGIN_OBJDATAAREA_MAP(CTestModule)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_TestModuleDataArea1, m_DataArea1)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
CTestModule::CTestModule()
{
///<AutoGeneratedContent id="MemberInitialization">
	memset(&m_DataArea1, 0, sizeof(m_DataArea1));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
CTestModule::~CTestModule() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CTestModule)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CTestModule::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CTestModule::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CTestModule::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CTestModule::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}
