///////////////////////////////////////////////////////////////////////////////
// TMC_File_Test_ProjectServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_TMC_File_Test_Project = 0x3F000000;
#define SRVNAME_TMC_FILE_TEST_PROJECT "TMC_File_Test_Project"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_TMC_File_Test_ProjectCTestModule = {0x15743622,0xddbc,0x48fd,{0x9d,0x8b,0x46,0xf3,0xe4,0xe5,0x75,0x6f}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_0E5EA07F_6D6C_4E1D_AFF5_025127AC81E2_INCLUDED_)
#define _TC_TYPE_0E5EA07F_6D6C_4E1D_AFF5_025127AC81E2_INCLUDED_
#pragma pack(push,1)
typedef struct _MainStruct
{
	SHORT SubItem1;
	bool SubItem2;
	unsigned char SubItem3 : 1;
	unsigned char reserved1 : 7;
	BYTE SubItem4;
	unsigned char reserved2[3];
	double SubItem5;
	SHORT SubItem6;
	SHORT SubItem7;
	SHORT SubItem8;
	SHORT SubItem9;
	SHORT SubItem10;
	SHORT addedmore;
	SHORT subitems;
} MainStruct, *PMainStruct;
#pragma pack(pop)
#endif // !defined(_TC_TYPE_0E5EA07F_6D6C_4E1D_AFF5_025127AC81E2_INCLUDED_)

#pragma pack(push,1)
typedef struct _TestModuleDataArea1
{
	SHORT dfe;
	SHORT werq;
	MainStruct MainVariable;
	MainStruct differentOne;
} TestModuleDataArea1, *PTestModuleDataArea1;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_TestModuleDataArea1 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
