///////////////////////////////////////////////////////////////////////////////
// TMC_File_Test_ProjectInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "TMC_File_Test_ProjectServices.h"

///<AutoGeneratedContent id="Interfaces">
///</AutoGeneratedContent>
