///////////////////////////////////////////////////////////////////////////////
// TMC_File_Test_ProjectClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "TMC_File_Test_ProjectClassFactory.h"
#include "TMC_File_Test_ProjectServices.h"
#include "TMC_File_Test_ProjectVersion.h"
#include "TestModule.h"

BEGIN_CLASS_MAP(CTMC_File_Test_ProjectClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_TMC_File_Test_Project, CID_TMC_File_Test_ProjectCTestModule, SRVNAME_TMC_FILE_TEST_PROJECT "!CTestModule", CTestModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CTMC_File_Test_ProjectClassFactory::CTMC_File_Test_ProjectClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_TMC_FILE_TEST_PROJECT));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(TMC_File_Test_Project));
#endif //defined(TCDBG_UNIT_VERSION)
}

